//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assigment01.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assigment01.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft®.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to piilota selitys.
        /// </summary>
        public static string HideExplanation {
            get {
                return ResourceManager.GetString("HideExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook App.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varoitus: Valitsemalla tämän asetuksen vahvistat, että tämä puhelin on organisaatiosi tietoturvakäytännön mukainen..
        /// </summary>
        public static string PrivatePhoneWarning {
            get {
                return ResourceManager.GetString("PrivatePhoneWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to näytä selitys.
        /// </summary>
        public static string ShowExplanation {
            get {
                return ResourceManager.GetString("ShowExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yksityinen puhelin.
        /// </summary>
        public static string ThisIsPrivatePhone {
            get {
                return ResourceManager.GetString("ThisIsPrivatePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valitse tämä asetus, jos olet tämän puhelimen ainoa käyttäjä. Palvelimesi sallii tavallista pidemmän käyttämättömyysajan, ennen kuin sinut kirjataan ulos..
        /// </summary>
        public static string ThisIsPrivatePhoneInfo {
            get {
                return ResourceManager.GetString("ThisIsPrivatePhoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julkinen puhelin.
        /// </summary>
        public static string ThisIsPublicPhone {
            get {
                return ResourceManager.GetString("ThisIsPublicPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valitse tämä vaihtoehto, jos käytät Outlook Appiä julkisessa puhelimessa. Kun olet lopettanut, muista kirjautua ulos ja sulkea sovellus istuntosi päätteeksi..
        /// </summary>
        public static string ThisIsPublicPhoneInfo {
            get {
                return ResourceManager.GetString("ThisIsPublicPhoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suojaus.
        /// </summary>
        public static string TitleProtection {
            get {
                return ResourceManager.GetString("TitleProtection", resourceCulture);
            }
        }
    }
}
