//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assigment01.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assigment01.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft®.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here..
        /// </summary>
        public static string ClickMeWithDot {
            get {
                return ResourceManager.GetString("ClickMeWithDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to Microsoft Exchange.
        /// </summary>
        public static string ConnectedToMsExchange {
            get {
                return ResourceManager.GetString("ConnectedToMsExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide explanation.
        /// </summary>
        public static string HideExplanation {
            get {
                return ResourceManager.GetString("HideExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login done.
        /// </summary>
        public static string LoginDone {
            get {
                return ResourceManager.GetString("LoginDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid username and password.
        /// </summary>
        public static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2010 Microsoft Corporation. All rights reserved..
        /// </summary>
        public static string MSCopyright2010 {
            get {
                return ResourceManager.GetString("MSCopyright2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook App.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordWithColon {
            get {
                return ResourceManager.GetString("PasswordWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: By selecting this option, you confirm that this computer complies with your organization&apos;s security policy..
        /// </summary>
        public static string PrivatePhoneWarning {
            get {
                return ResourceManager.GetString("PrivatePhoneWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show explanation.
        /// </summary>
        public static string ShowExplanation {
            get {
                return ResourceManager.GetString("ShowExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a private phone.
        /// </summary>
        public static string ThisIsPrivatePhone {
            get {
                return ResourceManager.GetString("ThisIsPrivatePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option if you&apos;re the only person who uses this phone. Your server will allow a longer period of inactivity before signing you out..
        /// </summary>
        public static string ThisIsPrivatePhoneInfo {
            get {
                return ResourceManager.GetString("ThisIsPrivatePhoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a public or shared phone.
        /// </summary>
        public static string ThisIsPublicPhone {
            get {
                return ResourceManager.GetString("ThisIsPublicPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option if you use Outlook App on a public phone. Be sure to sign out when you&apos;ve finished and close all windows to end your session..
        /// </summary>
        public static string ThisIsPublicPhoneInfo {
            get {
                return ResourceManager.GetString("ThisIsPublicPhoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string TitleProtection {
            get {
                return ResourceManager.GetString("TitleProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the light version of Outlook App.
        /// </summary>
        public static string UsePhoneAppLight {
            get {
                return ResourceManager.GetString("UsePhoneAppLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The light version of Outlook App includes fewer features. Use it if you&apos;re on a slow connection or using a phone with unusually strict browser security settings. We also support the full Outlook App experience on some browsers on Windows, Mac, and Linux phones. To check out all the supported browsers and operating systems, .
        /// </summary>
        public static string UsePhoneLightInfo {
            get {
                return ResourceManager.GetString("UsePhoneLightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string UserNameWithColon {
            get {
                return ResourceManager.GetString("UserNameWithColon", resourceCulture);
            }
        }
    }
}
